### ISSUE TITLE
random seeds， iterations

### ISSUE THREAD

**Issue by cherryolg** [EricFH/SOR#4]
Hello, author, do you set random seeds during training? In addition, is the experimental result of your paper selected 54000 iterations? When I ran the training code, I found that the best result was not iterating to the last time, but iterating to 50,000 times when both metrics were good. I hope you could help me answer these questions.

**Comment by EricFH** [comment]
I do not set certain random seeds and my iteration is set to 54000. There are some small differences in different iterations, which is a normal phenomenon. Although there are some differences, I think results do not differ much and they are still outperform former methods.
